require('settings')
require('keymaps')
require('plugins')
-- require('config.catppuccin')
-- require('config.tokyonight')
require('config.gruvbox')
require('config.cmp')
require('config.mason')
require('config.treesitter')
require('config.nvim-tree')
require('config.telescope')
require('config.lsp')
require('config.lualine')
require('config.alpha')
require('config.gitsigns')
require('config.presence')
require('config.toggleterm')
